###################################################################
### https://wiki.hyprland.org/Configuring/Configuring-Hyprland/ ###
###################################################################

source = ~/.config/hypr/mocha.conf

preload = $HOME/hyprland-dotfiles/wallpapers/Sunset-room.png
wallpaper = HDMI-A-1, $HOME/hyprland-dotfiles/wallpapers/Sunset-room.png
splash = true
splash_offset = 20
splash_opacity = 0.8
ipc = true
